server:
  port: 9000

express:
  basedir: "app"
  app: "app.js"
  routes: "routes"
  views: "views"
  statics: "../public"
  includes: "../public/includes"

statics:
  src: "app/assets"
  tmp: ".tmp"
  dist: "public"

livereload:
  port: 35729
  excludeList:
    - ".woff"
    - ".js"
    - ".css"
    - ".ico"

hooks:
  dir: ".hooks"
  livereload: "livereload"
